export const names = [
    "Gaynelle Delreal",
    "Donnie Gisi",
    "Jefferson Jennette",
    "Daniele Cogburn",
    "Sherril Hinz",
    "Lucienne Claassen",
    "Laurinda Giampaolo",
    "Toshia Lillibridge",
    "Kymberly Selfridge",
    "Aracely Fonda",
    "Lisbeth Bredeson",
    "Leonie Canino",
    "Willie Baginski",
    "Lacie Knop",
    "Debora Orsborn",
    "Ivana Jackson",
    "Lilly Didier",
    "Shea Dickerson",
    "Gerry Yant",
    "Kathe Pratts",
    "Minerva Plumb",
    "Arica Breslin",
    "Lucinda Dresel",
    "Robbyn Grumbles",
    "Signe Lovette",
    "Tyler Parks",
    "Long Keene",
    "Amber Wright",
    "Chieko Ruse",
    "Cody Villalobos",
    "Lynette Aguirre",
    "Rosana Hayworth",
    "Carlee Starnes",
    "Sharon Grossi",
    "Mitzie Erhart",
    "Natalia Nack",
    "Ina Westerman",
    "Adina Sallee",
    "Gerri Shadwick",
    "Eleonora Papas",
    "Princess Greenidge",
    "Otha Proulx",
    "Ruben Lytch",
    "Vania Vester",
    "Jillian Wherry",
    "Xiao Litherland",
    "Clement Harrington",
    "Roxana Gledhill",
    "Hayden Lineberry",
    "Gaylord Musick",
    "Gaynelle Delreal",
    "Donnie Gisi",
    "Jefferson Jennette",
    "Daniele Cogburn",
    "Sherril Hinz",
    "Lucienne Claassen",
    "Laurinda Giampaolo",
    "Toshia Lillibridge",
    "Kymberly Selfridge",
    "Aracely Fonda",
    "Lisbeth Bredeson",
    "Leonie Canino",
    "Willie Baginski",
    "Lacie Knop",
    "Debora Orsborn",
    "Ivana Jackson",
    "Lilly Didier",
    "Shea Dickerson",
    "Gerry Yant",
    "Kathe Pratts",
    "Minerva Plumb",
    "Arica Breslin",
    "Lucinda Dresel",
    "Robbyn Grumbles",
    "Signe Lovette",
    "Tyler Parks",
    "Long Keene",
    "Amber Wright",
    "Chieko Ruse",
    "Cody Villalobos",
    "Lynette Aguirre",
    "Rosana Hayworth",
    "Carlee Starnes",
    "Sharon Grossi",
    "Mitzie Erhart",
    "Natalia Nack",
    "Ina Westerman",
    "Adina Sallee",
    "Gerri Shadwick",
    "Eleonora Papas",
    "Princess Greenidge",
    "Otha Proulx",
    "Ruben Lytch",
    "Vania Vester",
    "Jillian Wherry",
    "Xiao Litherland",
    "Clement Harrington",
    "Roxana Gledhill",
    "Hayden Lineberry",
    "Gaylord Musick",
];

export const desc = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Nunc dapibus nunc eget neque vehicula, ut blandit nisl commodo.",
    "Nam et diam tincidunt, finibus lorem ac, interdum diam.",
    "Mauris quis est eu ipsum pellentesque tempor.",
    "Fusce faucibus est quis ante vehicula, quis maximus odio egestas.",
    "Nunc in dui vel leo varius euismod eget vestibulum leo.",
    "Integer placerat magna in metus pulvinar tempor.",
    "Ut auctor neque vel tincidunt fermentum.",
    "Nulla aliquam magna eu consectetur viverra.",
    "Pellentesque a nunc ut sapien posuere tempor vitae et nulla.",
    "Nulla porttitor dui scelerisque tortor cursus congue.",
    "Nullam hendrerit leo a facilisis cursus.",
    "Proin varius urna quis egestas iaculis.",
    "Etiam volutpat sapien quis lacus faucibus, quis faucibus purus sollicitudin.",
    "Vivamus et libero aliquet nibh convallis elementum vel nec ante.",
    "Suspendisse vitae enim accumsan turpis auctor porttitor.",
    "Sed eu urna et ligula semper elementum.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Nunc dapibus nunc eget neque vehicula, ut blandit nisl commodo.",
    "Nam et diam tincidunt, finibus lorem ac, interdum diam.",
    "Mauris quis est eu ipsum pellentesque tempor.",
    "Fusce faucibus est quis ante vehicula, quis maximus odio egestas.",
    "Nunc in dui vel leo varius euismod eget vestibulum leo.",
    "Integer placerat magna in metus pulvinar tempor.",
    "Ut auctor neque vel tincidunt fermentum.",
    "Nulla aliquam magna eu consectetur viverra.",
    "Pellentesque a nunc ut sapien posuere tempor vitae et nulla.",
    "Nulla porttitor dui scelerisque tortor cursus congue.",
    "Nullam hendrerit leo a facilisis cursus.",
    "Proin varius urna quis egestas iaculis.",
    "Etiam volutpat sapien quis lacus faucibus, quis faucibus purus sollicitudin.",
    "Vivamus et libero aliquet nibh convallis elementum vel nec ante.",
    "Suspendisse vitae enim accumsan turpis auctor porttitor.",
    "Sed eu urna et ligula semper elementum.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Nunc dapibus nunc eget neque vehicula, ut blandit nisl commodo.",
    "Nam et diam tincidunt, finibus lorem ac, interdum diam.",
    "Mauris quis est eu ipsum pellentesque tempor.",
    "Fusce faucibus est quis ante vehicula, quis maximus odio egestas.",
    "Nunc in dui vel leo varius euismod eget vestibulum leo.",
    "Integer placerat magna in metus pulvinar tempor.",
    "Ut auctor neque vel tincidunt fermentum.",
    "Nulla aliquam magna eu consectetur viverra.",
    "Pellentesque a nunc ut sapien posuere tempor vitae et nulla.",
    "Nulla porttitor dui scelerisque tortor cursus congue.",
    "Nullam hendrerit leo a facilisis cursus.",
    "Proin varius urna quis egestas iaculis.",
    "Etiam volutpat sapien quis lacus faucibus, quis faucibus purus sollicitudin.",
    "Vivamus et libero aliquet nibh convallis elementum vel nec ante.",
    "Suspendisse vitae enim accumsan turpis auctor porttitor.",
    "Sed eu urna et ligula semper elementum.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Nunc dapibus nunc eget neque vehicula, ut blandit nisl commodo.",
    "Nam et diam tincidunt, finibus lorem ac, interdum diam.",
    "Mauris quis est eu ipsum pellentesque tempor.",
    "Fusce faucibus est quis ante vehicula, quis maximus odio egestas.",
    "Nunc in dui vel leo varius euismod eget vestibulum leo.",
    "Integer placerat magna in metus pulvinar tempor.",
    "Ut auctor neque vel tincidunt fermentum.",
    "Nulla aliquam magna eu consectetur viverra.",
    "Pellentesque a nunc ut sapien posuere tempor vitae et nulla.",
    "Nulla porttitor dui scelerisque tortor cursus congue.",
    "Nullam hendrerit leo a facilisis cursus.",
    "Proin varius urna quis egestas iaculis.",
    "Etiam volutpat sapien quis lacus faucibus, quis faucibus purus sollicitudin.",
    "Vivamus et libero aliquet nibh convallis elementum vel nec ante.",
    "Suspendisse vitae enim accumsan turpis auctor porttitor.",
    "Sed eu urna et ligula semper elementum."
]
